<div id="openpos-split-payment">

    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <?php foreach($magewire->paymentMethods as $code => $paymentMethod): ?>
            <div class="w-full">
                <span class="text-black"><?= $paymentMethod['title'] ?></span>
                <input type="tel" class="w-full form-input" id="<?=$code?>.amount" wire:model.defer="paymentMethods.<?=$code?>.amount">
            </div>
        <?php endforeach; ?>
    </div>

    <div class="flex flex-wrap">
        <button class="btn btn-primary btn-secondary w-full" wire:click="save"><?php echo __('Apply'); ?></button>
    </div>

    <?php if($magewire->getTotalRemaining(false) > 0): ?>
        <div class="mt-4">
            <p class="font-bold">Outstanding balance: <?= $magewire->getTotalRemaining(true) ?></p>
            <input type="checkbox" id="ignore_outstanding_balance" wire:model="ignoreOutstandingBalance">
            <span>Ignore outstanding balance</span>
        </div>
    <?php endif; ?>

</div>
